eyetracking/urls.py
## urls.py
from django.conf.urls import url

from . import views

app_name = 'eyetracking'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^join-the-dots/$', views.dots, name='join-the-dots'),
    url(r'^join-the-dots/results/$', views.joined_dots, name='join-the-dots-results'),
    url(r'^mouse-controller/$', views.controller.as_view(), name='mouse-controller'),
    url(r'^reading-analysis/$', views.reading, name='reading-analysis'),
    url(r'^reading-analysis/results/$', views.reading_gaze, name='reading-analysis-results'),
    url(r'^image-viewing/$', views.image, name='image-viewing'),
    url(r'^image-viewing/results/$', views.image_gaze, name='image-viewing-results'),
]

hccworkshop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from home.forms import LoginForm

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('home.urls')),
    url(r'^login/$', auth_views.login, {'template_name':'home/login.html', 'authentication_form':LoginForm}, name='login'),
    url(r'^logout/$', auth_views.logout, {'template_name':'home/logout.html'}, name='logout'),
    url(r'^eye-tracking/', include('eyetracking.urls')),
    url(r'^cyber-security/', include('cybersecurity.urls')),
    url(r'^the-thatcher-effect/', include('thatcher.urls')),
    url(r'^experiment/infovis/', include('collection.urls')),
    url(r'^human-computer-interaction/', include('design.urls')),
    url(r'^image-manipulation/', include('image_manipulation.urls')),
    url(r'^neural-networks/', include('neural_networks.urls')),
    url(r'^experiment/infovis/', include('collection.urls')),
    url(r'^surveys/', include('surveys.urls')),
]

admin.site.site_header = 'HCC Workshop Administration'

home/urls.py
from django.conf.urls import url
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm

from . import views

app_name = 'home'
urlpatterns = [
    url(r'^$', views.Index.as_view(), name='index'),
    url(r'^dashboard$', views.dashboard, name='dashboard'),
    url(r'^about$', views.About.as_view(), name='about'),
    url(r'^register$', views.register, name='register'),
    # url(r'^pdf$', views.get_report, name='pdf'),
    url(r'^eyegazeinfo/$', views.eyegazeinfo, name='eyegazeinfo'),
    url(r'^newsletter$', views.newsletter, name='newsletter'),
    # url(r'^other-research$', views.OtherResearch.as_view(), name='other_research'),
    url(r'^ecg$', views.ecg.as_view(), name='ecg'),
    url(r'^ecg/empatica-ecg-activity$', views.ecg_activity, name='ecg-activity'),
    url(r'^eeg$', views.eeg.as_view(), name='eeg'),
    url(r'^eeg/emotiv-activity$', views.eeg_activity, name='eeg-activity'),
    url(r'^eda$', views.eda.as_view(), name='eda'),
    url(r'^eda/empatica-eda-activity$', views.eda_activity, name='eda-activity'),
    url(r'^gestures$', views.gestures.as_view(), name='gestures'),
    url(r'^gestures/gestures-activity$', views.gestures_activity, name='gestures-activity'),
    url(r'^driving-simulator$', views.driving_simulator.as_view(), name='driving-simulator'),
    url(r'^driving-simulator/driving-activity$', views.driving_activity, name='driving-activity'),
    url(r'^interface-design$', views.interface_design, name='interface-design'),
    url(r'^interface-design/evaluating-ereader-interfaces$', views.ereader_activity, name='ereader-activity'),
    url(r'^level-up$', views.levelUp, name='levelup'),
]

eyetracking/models.py
from django.db import models
from django.contrib.auth.models import User

class DotsGaze(models.Model):
    user = models.ForeignKey(User)
    timestamp = models.DateTimeField('Time Collected',auto_now_add=True)
    gazedata = models.TextField()

class ReadingGaze(models.Model):
    user = models.ForeignKey(User)
    timestamp = models.DateTimeField('Time Collected',auto_now_add=True)
    gazedata = models.TextField()

class ImageGaze(models.Model):
    user = models.ForeignKey(User)
    timestamp = models.DateTimeField('Time Collected',auto_now_add=True)
    image1 = models.TextField()
    image2 = models.TextField()
    image3 = models.TextField()

eyetracking/forms.py
from django import forms

from eyetracking.models import DotsGaze, ReadingGaze, ImageGaze

# For the join the dots app
class DotsGazeForm(forms.ModelForm):
    class Meta:
        model = DotsGaze
        fields = ['gazedata']

# For the reading tracking app
class ReadingGazeForm(forms.ModelForm):
    class Meta:
        model = ReadingGaze
        fields = ['gazedata']

# For image tracking apply
class ImageGazeForm(forms.ModelForm):
    class Meta:
        model = ImageGaze
        fields = ['image1','image2','image3']

eyetracking/views.py
## views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.views import generic
from .forms import DotsGazeForm, ReadingGazeForm, ImageGazeForm
from .models import DotsGaze, ReadingGaze, ImageGaze
import json
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

@login_required
def index(request):
    sum = 2 + 2
    context = {'sum': sum}
    return render(request, 'eyetracking/index.html', context)

# For the join the dots app
@login_required
def dots(request):
    if request.method == 'POST':
        form = DotsGazeForm(request.POST)
        if form.is_valid():
            eyegaze_form = form.save(commit=False)
            eyegaze_form.user = request.user
            eyegaze_form.save()
            return HttpResponseRedirect('/eye-tracking/join-the-dots/results')
    else:
        form = DotsGazeForm()
    
    return render(request,'eyetracking/join_the_dots.html', {'form':form})
    
# For the join the dots app
@login_required
def joined_dots(request):
    # get most recent gaze data from the db
    rawgaze = DotsGaze.objects.filter(user=request.user.id).order_by('-timestamp')[0]
    # extract the gaze data 
    gazedata = rawgaze.gazedata
    # create the x and y coords for plotting with D3
    list_for_d3 = []
    json1 = json.loads(gazedata)
    for i in range(0,len(json1)): ## Get each frame
            json2 = json.loads(json1[i]) # a single frame
            if (json2["fix"]): # only using fixation data
                list_for_d3.append({"x" : json2["avg"]["x"], "y":json2["avg"]["y"]})

    context = {"data":list_for_d3}
    return render(request,'eyetracking/joined_dots.html', context)

# For eye controller app
@method_decorator(login_required, name='dispatch')
class controller(generic.TemplateView):
    template_name = 'eyetracking/controller.html'

# For Reading Tracking app
@login_required
def reading(request):
    if request.method == 'POST':
        form = ReadingGazeForm(request.POST)
        if form.is_valid():
            eyegaze_form = form.save(commit=False)
            eyegaze_form.user = request.user
            eyegaze_form.save()
            return HttpResponseRedirect('/eye-tracking/reading-analysis/results')
    else:
        form = ReadingGazeForm()
    
    return render(request,'eyetracking/reading.html', {'form':form})

# Plot the participants eye gaze onto the text and show them
@login_required
def reading_gaze(request):
    # get most recent gaze data from the db
    rawgaze = ReadingGaze.objects.filter(user=request.user.id).order_by('-timestamp')[0]
    # extract the gaze data 
    gazedata = rawgaze.gazedata
    # create the x and y coords for plotting with D3
    list_for_d3 = []
    json1 = json.loads(gazedata)
    for i in range(0,len(json1)): ## Get each frame
            json2 = json.loads(json1[i]) # a single frame
            if (json2["fix"]): # only using fixation data
                list_for_d3.append({"x" : json2["avg"]["x"], "y":json2["avg"]["y"]})

    context = {"data":list_for_d3}
    return render(request,'eyetracking/reading_gaze.html', context)

# For image tracking app
@login_required
def image(request):
    if request.method == 'POST':
        form = ImageGazeForm(request.POST)
        if form.is_valid():
            eyegaze_form = form.save(commit=False)
            eyegaze_form.user = request.user
            eyegaze_form.save()
            return HttpResponseRedirect('/eye-tracking/image-viewing/results')
    else:
        form = ImageGazeForm()
    
    return render(request,'eyetracking/image.html', {'form':form})

# Plot the participants eye gaze onto the text and show them
@login_required
def image_gaze(request):
     # get most recent gaze data from the db
    rawgaze = ImageGaze.objects.filter(user=request.user.id).order_by('-timestamp')[0]
    # extract the gaze data 
    image1_gazedata = rawgaze.image1
    image2_gazedata = rawgaze.image2
    image3_gazedata = rawgaze.image3
    # create the x and y coords for plotting with D3
    img1_data = processGazedata(image1_gazedata)
    img2_data = processGazedata(image2_gazedata)
    img3_data = processGazedata(image3_gazedata)

    context = {"img1_data": img1_data, "img2_data": img2_data, "img3_data": img3_data}
    return render(request,'eyetracking/image_gaze.html', context)

def processGazedata(gazedata):
    list_for_d3 = []
    json1 = json.loads(gazedata)
    for i in range(0,len(json1)): ## Get each frame
            json2 = json.loads(json1[i]) # a single frame
            if (json2["fix"]): # only using fixation data
                list_for_d3.append({"x" : json2["avg"]["x"], "y":json2["avg"]["y"]})

    return list_for_d3

## DEV PAGES TO RECREATE GIFS
# To display the reading tracking gif
@login_required
def reading_gif(request):
    return render(request,'eyetracking/reading_gif.html')

# To display the join the dots gif 
@login_required
def dots_gif(request):
    return render(request,'eyetracking/dots_gif.html')

eyetracking/templates/eyetracking/image.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %} HCC Workshop | Eye Tracking | Image Viewing{% endblock %}

{% block head %} 
<link rel="stylesheet" href="{% static 'eyetracking/styles.css' %}">

<style>
svg { 
	border: 1px solid red;
	/*margin-left: 302px;
	background:transparent;
	position: absolute;
	display: block;
	z-index: 50;*/
}
</style>
{% endblock %}

{% block app-breadcrumbs %}
    <li><a href="{% url 'eyetracking:index' %}">Eye Tracking</a></li>
	<li class="active">Image Viewing</li>
{% endblock %}

{% block content %} 

    <div class="page-header">
        <h1>Eye Tracking <small>Image Viewing</small></h1>
    </div>
		<div class="container-fluid app-text-standard" style="height: 70vh">
			<p class="test-justify">When we usually look at an image, our eyes don't actually see very much of the fine details. Instead, it has been found that what we actually focus on and view in an image is dependent on the goals we have when we look at it.</p>
			<p class="test-justify">You will be shown the same image three times, but each time you will be asked a different question. Afterward, you will be able to visualise your eye gaze to see how your eye movements varied depending on the three different goals you were given, even though the image was identical.</p>
			<section class="text-center button-section" id="experiment-button" >
				<a href="#experiment_p1" id="to_pt1" role="button" class="btn btn-primary btn-lg"><span>Try it out</span><br><i class="fa fa-chevron-down" aria-hidden="true"></i></a>
			</section>
		</div>

		<div id="experiment_p1" class="container-fluid app-text-standard" >
            <p class="text-center lead">Please look at this image and when you are ready press the Next button.</p>   
            <div class="text-center" id="test">
				<img id="img1" src="{% static 'eyetracking/the_visitor.jpg' %}" alt="The Visitor" />
			</div>
			<form method="post" action="">
			{% csrf_token %}
			{{ form.image1.as_hidden }}
			<section class="text-center button-section" id="experiment-button">
				<a href="#experiment_p2" role="button" id="to_pt2" class="btn btn-primary btn-lg"><span>Next</span><i class="fa fa-chevron-right" aria-hidden="true"></i></a>
			</section>
		</div>

        <!--<svg class="overlay"> </svg>-->
        <div id="experiment_p2"  class="container-fluid app-text-standard">
            <p class="text-center lead">Look again at the image, this time can you guess what the ages of the people in the picture are?</p>   
            <div class="text-center"><img id="img2" src="{% static 'eyetracking/the_visitor.jpg' %}" alt="The Visitor" /></div>
			{{ form.image2.as_hidden }}
			<section class="text-center button-section" id="experiment-button">
				<a href="#experiment_p3" role="button" id="to_pt3" class="btn btn-primary btn-lg"><span>Next</span><i class="fa fa-chevron-right" aria-hidden="true"></i></a>
			</section>
		</div>

		<div id="experiment_p3"  class="container-fluid app-text-standard">
            <p class="text-center lead">Look again at the image, this time memorise the positions of the objects in the room.</p>   
            <div class="text-center"><img src="{% static 'eyetracking/the_visitor.jpg' %}" alt="The Visitor" /></div>
			{{ form.image3.as_hidden }}
			<section class="text-center button-section" id="experiment-button">
				<button type="submit" value="Next" class="btn btn-primary btn-lg">See my eye gaze <i class="fa fa-chevron-right" aria-hidden="true"></i></button>
			</section>
		</form>
		</div>
{% endblock %}

{% block script %} 
<script src="https://d3js.org/d3.v4.min.js"></script>
<script type="text/javascript" src="{% static 'eyetracking/scroll.js' %}"></script>
<script>

$( document ).ready(function() {
		console.log( "ready!" );

        // get coordinates of image on the screen
        var x = $("#img1").position().left-100;
        var y = $("#img1").position().top-$(window).height()+50;
        var width = $("#img1").width();
        var height = $("#img1").height();
        console.log("x = ", x, ", y = ", y);

        var x2 = $("#img2").position().left-100;
        var y2 = $("#img2").position().top-($(window).height()*2)+50;
        var w2 = $("#img2").width();
        var h2 = $("#img2").height();
        console.log("x2 = ", x2, ", y2 = ", y2);
        // test if eye gaze point is within the coordinates

        // apply transform and store data
	
        // var svgContainer = d3.select(".overlay");

        // var nodes = [{"x": x, "y": y}];

        // svgContainer.append("circle")
        //                 .data(nodes)
        //                 .attr("class", "node")
        //                 .attr("cx", function(d) { return d.x;})
        //                 .attr("cy", function(d) { return d.y;})                 
        //                 .attr("r", "10");

        var eyedata_p1 = [];
        var eyedata_p2 = [];
        var eyedata_p3 = [];

        image1 = $('#id_image1');
        image2 = $('#id_image2');
        image3 = $('#id_image3');

        var stop_1 = false;
        var stop_2 = false;

        $('#to_pt1').click(function() {
            console.log("now collecting for part 1");
            EyeTribe.loop(function(frame) {
                if (stop_1) return;
                // console.log(frame);
                eyedata_p1.push(frame.dump());
                image1.val(JSON.stringify(eyedata_p1));
            });
        });

        $('#to_pt2').click(function() {
            stop_1=true;
            console.log("now collecting for part 2");
            EyeTribe.loop(function(frame) {
                if (stop_2) return;
                // console.log(frame);
                eyedata_p2.push(frame.dump());
                image2.val(JSON.stringify(eyedata_p2));
            });
        });

        $('#to_pt3').click(function() {
            stop_2=true;
            console.log("now collecting for part 3");
            EyeTribe.loop(function(frame) {
                // console.log(frame);
                eyedata_p3.push(frame.dump());
                image3.val(JSON.stringify(eyedata_p3));
            });
        });
    });
</script>
{% endblock %}

eyetracking/templates/eyetracking/image_gaze.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %} HCC Workshop | Image Tracking {% endblock %}

{% block head %} 
<link rel="stylesheet" href="{% static 'eyetracking/styles.css' %}">
<style>
.blue {
    fill: blue;
    stroke: royalblue;
    stroke-width: 1px;
}
.blue_path { 
    stroke:  royalblue;
    stroke-width: 2;
    fill: none;
}
.pink {
    fill: red;
    stroke: tomato;
    stroke-width: 1px;
}
.pink_path { 
    stroke:  tomato;
    stroke-width: 2;
    fill: none;
}
.green {
    fill: green;
    stroke: lightgreen;
    stroke-width: 1px;
}
.green_path { 
    stroke: lightgreen;
    stroke-width: 2;
    fill: none;
}

</style>
<style>
	body {
		overflow-y: scroll;
	}
</style>
{% endblock %}

{% block app-breadcrumbs %}
	<li><a href="{% url 'eyetracking:index' %}">Eye Tracking</a></li>
    <li><a href="{% url 'eyetracking:image-viewing' %}">Images</a></li>
	<li class="active">Results</li>
{% endblock %}

{% block content %} 

		<div class="container-fluid app-text-standard">
			<p class="text-center lead">Check out your eye gaze when you looked at the image each time: </p>   
            <div class="text-center" id="test">
				<img id="img1" src="{% static 'eyetracking/the_visitor.jpg' %}" alt="The Visitor" />
			</div>
            <p class="text-center"><span style="color: blue"><strong>Blue</strong></span> is when you could freely look at the image. <br><span style="color: red"><strong>Red</strong></span> is when you were looking at the people to try and guess their ages. <br><span style="color: green"><strong>Green</strong></span> is when you were looking at the objects to try and memorise their position.</p>
            <p class="text-center lead">Notice how they are slightly different?</p>
		</div>
        <section class="app-text-highlight">
	<div class="text-center vertical-align">
	    <h1>Level Up</h1>
		<p class="lead">Feast your eyes on this.</p>
		<button role="button" class="btn btn-default btn-lg" href="#" id="level-up"><span class="btn-primary-span">Level Up</span><i class="fa fa-level-up" aria-hidden="true"></i></a>
    </div>
</section>
{% endblock %}
{% block script %} 
<script src="https://d3js.org/d3.v4.min.js"></script>
<script>
// Plot the gaze data from the previous screen using D3.js:
data1 = {{ img1_data|safe }};
data2 = {{ img2_data|safe }};
data3 = {{ img3_data|safe }};

//This is the accessor function we talked about above
var lineFunction = d3.line()
						.x(function(d) { return d.x; })
						.y(function(d) { return d.y; });

 
//The SVG Container
var svgContainer = d3.select("body").append("svg")
					.attr("width", "100vw")
					.attr("height", "100vh")
					.attr("class", "overlay");

// Plot the data from Image 1
var b_lineGraph = svgContainer.append("path")
						.attr("d", lineFunction(data1))
						.attr("class", "blue_path")
						.attr("stroke-width", 2)
						.attr("fill", "none");	

var b_circles = svgContainer.selectAll("circle").filter(".blue")
                          .data(data1)
                          .enter()
                          .append("circle");

var b_circleAttributes = b_circles
                       .attr("cx", function (d) { return d.x; })
                       .attr("cy", function (d) { return d.y; })
                       .attr("class", "blue")
                       .attr("r", 5);

// Plot the data from Image 2
var p_lineGraph = svgContainer.append("path")
						.attr("d", lineFunction(data2))
						.attr("class", "pink_path")
						.attr("stroke-width", 2)
						.attr("fill", "none");	

var p_circles = svgContainer.selectAll("circle").filter(".pink")
                          .data(data2)
                          .enter()
                          .append("circle");

var p_circleAttributes = p_circles
                       .attr("cx", function (d) { return d.x; })
                       .attr("cy", function (d) { return d.y; })
                       .attr("class", "pink")
                       .attr("r", 5);

// Plot gaze from image 3
var g_lineGraph = svgContainer.append("path")
						.attr("d", lineFunction(data3))
						.attr("class", "green_path")
						.attr("stroke-width", 2)
						.attr("fill", "none");	

var g_circles = svgContainer.selectAll("circle").filter(".green")
                          .data(data3)
                          .enter()
                          .append("circle");

var g_circleAttributes = g_circles
                       .attr("cx", function (d) { return d.x; })
                       .attr("cy", function (d) { return d.y; })
                       .attr("class", "green")
                       .attr("r", 5);

</script>
{% endblock %}

eyetracking/templates/eyetracking/join_the_dots.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %} HCC Workshop | Eye Tracking | Join The Dots{% endblock %}
{% block head %} 
    <link rel="stylesheet" href="{% static 'eyetracking/styles.css' %}">
{% endblock %}

{% block app-title %}Join The Dots{% endblock %}

{% block app-breadcrumbs %}
    <li><a href="{% url 'eyetracking:index' %}">Eye Tracking</a></li>
	<li class="active">Join The Dots</li>
{% endblock %}

{% block content %} 
   <div class="page-header">
        <h1>Eye Tracking <small>Join the dots</small></h1>
    </div>

        <div class="container-fluid app-text-standard" style="height: 70vh">
            <p class="text-justify">Do you remember those classic join-the-dot activities? By using eye tracking technology, we can actually record where on the screen you look, and use that information to join the dots for you!</p> 
            <p class="text-justify">Focus your eyes on each point on the screen as it appears. After you are done, the path which your eyes took will be displayed back to you in order to achieve a 'join-the-dots' effect. </p>
            <section class="text-center button-section" id="experiment-button">
                <a id="start" href="#experiment" role="button" class="btn btn-primary btn-lg"><span>Try it out</span><br><i class="fa fa-chevron-down" aria-hidden="true"></i></a>
            </section>
        </div>
          
        <div id="experiment" class="container">
            <div id="map"></div>
        
            <form method="post" action="">
                {% csrf_token %}
                {{ form.gazedata.as_hidden }}
                <div class="container-fluid next-page text-center">
                <button type="submit" id="next" value="Next" class="btn btn-primary btn-lg"><span class="btn-primary-span">View Results</span> <i class="fa fa-chevron-right" aria-hidden="true"></i></button>
                </div>
            </form>
            <p></p>
        <!--</div>-->

{% endblock %}

{% block script %} 
<script src="https://d3js.org/d3.v4.min.js"></script>
	<script type="text/javascript" src="{% static 'eyetracking/scroll.js' %}"></script>
    <script>
    var nodes = [{"x": screen.width*0.05, "y": screen.height*0.05}, {"x": screen.width*0.05,"y": screen.height*0.5}, 
                {"x": screen.width*0.05,"y": screen.height*0.25}, {"x": screen.width*0.25,"y": screen.height*0.25}, 
                {"x": screen.width*0.25,"y": screen.height*0.05}, {"x": screen.width*0.25,"y": screen.height*0.5}, 
                {"x": screen.width*0.55,"y": screen.height*0.5}, {"x": screen.width*0.47,"y": screen.height*0.5}, 
                {"x": screen.width*0.375,"y": screen.height*0.4}, {"x": screen.width*0.33,"y": screen.height*0.25}, 
                {"x": screen.width*0.375,"y": screen.height*0.11}, {"x": screen.width*0.47,"y": screen.height*0.05}, 
                {"x": screen.width*0.55,"y": screen.height*0.05}, 
                {"x": screen.width*0.87,"y": screen.height*0.05}, {"x": screen.width*0.8,"y": screen.height*0.05},
                {"x": screen.width*0.7,"y": screen.height*0.11}, {"x": screen.width*0.65,"y": screen.height*0.25}, 
                {"x": screen.width*0.7,"y": screen.height*0.4}, {"x":screen.width*0.8,"y": screen.height*0.5}, 
                {"x": screen.width*0.87,"y": screen.height*0.5},
                {"x": -100,"y": -100}]

    var eyedata = [];
    etdata = $('#id_gazedata');
    $('#start').click(function() {
        console.log("now collecting");
        EyeTribe.loop(function(frame) {
                eyedata.push(frame.dump());
                etdata.val(JSON.stringify(eyedata));
            });
            
        var svg = d3.select("#map").append("svg")
                    .attr("width", "90vw")
                    .attr("height", "70vh");
        nodes.forEach(function(d, i) {
            setTimeout(function() {
                var existing = d3.selectAll(".node")
                    .attr("fill", "white")
                svg.append("circle")
                    .datum(d)
                    .attr("class", "node")
                    .attr("cx", function(d) {
                        return d.x;
                    })
                    .attr("cy", function(d) {
                        return d.y;
                    })                 
                    .attr("r", "10");               
            }, 1500 * i);
        });
    });
</script>
{% endblock %}

eyetracking/templates/eyetracking/joined_dots.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %} HCC Workshop | Join the dots {% endblock %}

{% block head %} 
<link rel="stylesheet" href="{% static 'eyetracking/styles.css' %}">
<style>
	body {
		overflow-y: scroll;
	}
</style>
{% endblock %}

{% block app-breadcrumbs %}
    <li><a href="{% url 'eyetracking:index' %}">Eye Tracking</a></li>
	<li><a href="{% url 'eyetracking:join-the-dots' %}">Join the dots</a></li>
	<li class="active">Results</li>
{% endblock %}

{% block content %} 
	<div class="container-fluid " >
	<div id="showgaze" class="container">
		<div id="map"></div>
	</div>
	</div>
	<section class="app-text-highlight">
	<div class="text-center vertical-align">
	    <h1>Level Up</h1>
		<p class="lead">Feast your eyes on this.</p>
		<button role="button" class="btn btn-default btn-lg" href="#" id="level-up"><span class="btn-primary-span">Level Up</span><i class="fa fa-level-up" aria-hidden="true"></i></a>
    </div>
</section>
{% endblock %}
{% block script %} 
<script src="https://d3js.org/d3.v4.min.js"></script>
<script>
var nodes = [{"x": screen.width*0.05, "y": screen.height*0.05}, {"x": screen.width*0.05,"y": screen.height*0.5}, 
                {"x": screen.width*0.05,"y": screen.height*0.25}, {"x": screen.width*0.25,"y": screen.height*0.25}, 
                {"x": screen.width*0.25,"y": screen.height*0.05}, {"x": screen.width*0.25,"y": screen.height*0.5}, 
                {"x": screen.width*0.55,"y": screen.height*0.5}, {"x": screen.width*0.47,"y": screen.height*0.5}, 
                {"x": screen.width*0.375,"y": screen.height*0.4}, {"x": screen.width*0.33,"y": screen.height*0.25}, 
                {"x": screen.width*0.375,"y": screen.height*0.11}, {"x": screen.width*0.47,"y": screen.height*0.05}, 
                {"x": screen.width*0.55,"y": screen.height*0.05}, 
                {"x": screen.width*0.87,"y": screen.height*0.05}, {"x": screen.width*0.8,"y": screen.height*0.05},
                {"x": screen.width*0.7,"y": screen.height*0.11}, {"x": screen.width*0.65,"y": screen.height*0.25}, 
                {"x": screen.width*0.7,"y": screen.height*0.4}, {"x":screen.width*0.8,"y": screen.height*0.5}, 
                {"x": screen.width*0.87,"y": screen.height*0.5},
                {"x": -100,"y": -100}]

var svg = d3.select("#map").append("svg")
                    .attr("width", "100vw")
                    .attr("height", "70vh");
	nodes.forEach(function(d) {
			svg.append("circle")
				.datum(d)
				.attr("class", "node")
				.attr("cx", function(d) {
					return d.x;
				})
				.attr("cy", function(d) {
					return d.y;
				})                 
				.attr("r", "10");               
	});

// Plot the gaze data from the previous screen using D3.js:
data = {{ data|safe }};

//This is the accessor function we talked about above
var lineFunction = d3.line()
						.x(function(d) { return d.x; })
						.y(function(d) { return d.y; });
						
//The SVG Container
var svgContainer = d3.select("body").append("svg")
					.attr("width", "100vw")
					.attr("height", "80vh")
					.attr("class", "overlay");

//The line SVG Path we draw
var lineGraph = svgContainer.append("path")
						.attr("d", lineFunction(data))
						.attr("stroke", "blue")
						.attr("stroke-width", 2)
						.attr("fill", "none");	

var circles = svgContainer.selectAll("circle")
                          .data(data)
                          .enter()
                          .append("circle");

var circleAttributes = circles
                       .attr("cx", function (d) { return d.x; })
                       .attr("cy", function (d) { return d.y; })
                       .attr("r", 5)
					   .attr("class", "gaze")		  
</script>
{% endblock %}