design/urls.py
## urls.py
from django.conf.urls import url

from . import views

app_name = 'design'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^mappings/$', views.mappings, name='mappings'),
    url(r'^affordances/$', views.affordances, name='affordances'),
    url(r'^constraints/$', views.constraints, name='constraints'),
    url(r'^conceptual-model/$', views.conceptual, name='conceptual'),
]

hccworkshop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from home.forms import LoginForm

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('home.urls')),
    url(r'^login/$', auth_views.login, {'template_name':'home/login.html', 'authentication_form':LoginForm}, name='login'),
    url(r'^logout/$', auth_views.logout, {'template_name':'home/logout.html'}, name='logout'),
    url(r'^eye-tracking/', include('eyetracking.urls')),
    url(r'^cyber-security/', include('cybersecurity.urls')),
    url(r'^the-thatcher-effect/', include('thatcher.urls')),
    url(r'^experiment/infovis/', include('collection.urls')),
    url(r'^human-computer-interaction/', include('design.urls')),
    url(r'^image-manipulation/', include('image_manipulation.urls')),
    url(r'^neural-networks/', include('neural_networks.urls')),
    url(r'^experiment/infovis/', include('collection.urls')),
    url(r'^surveys/', include('surveys.urls')),
]

admin.site.site_header = 'HCC Workshop Administration'

home/urls.py
from django.conf.urls import url
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm

from . import views

app_name = 'home'
urlpatterns = [
    url(r'^$', views.Index.as_view(), name='index'),
    url(r'^dashboard$', views.dashboard, name='dashboard'),
    url(r'^about$', views.About.as_view(), name='about'),
    url(r'^register$', views.register, name='register'),
    # url(r'^pdf$', views.get_report, name='pdf'),
    url(r'^eyegazeinfo/$', views.eyegazeinfo, name='eyegazeinfo'),
    url(r'^newsletter$', views.newsletter, name='newsletter'),
    # url(r'^other-research$', views.OtherResearch.as_view(), name='other_research'),
    url(r'^ecg$', views.ecg.as_view(), name='ecg'),
    url(r'^ecg/empatica-ecg-activity$', views.ecg_activity, name='ecg-activity'),
    url(r'^eeg$', views.eeg.as_view(), name='eeg'),
    url(r'^eeg/emotiv-activity$', views.eeg_activity, name='eeg-activity'),
    url(r'^eda$', views.eda.as_view(), name='eda'),
    url(r'^eda/empatica-eda-activity$', views.eda_activity, name='eda-activity'),
    url(r'^gestures$', views.gestures.as_view(), name='gestures'),
    url(r'^gestures/gestures-activity$', views.gestures_activity, name='gestures-activity'),
    url(r'^driving-simulator$', views.driving_simulator.as_view(), name='driving-simulator'),
    url(r'^driving-simulator/driving-activity$', views.driving_activity, name='driving-activity'),
    url(r'^interface-design$', views.interface_design, name='interface-design'),
    url(r'^interface-design/evaluating-ereader-interfaces$', views.ereader_activity, name='ereader-activity'),
    url(r'^level-up$', views.levelUp, name='levelup'),
]

home/models.py
from django.db import models

from django.utils.timezone import now
from django.contrib.auth.models import User

from django.db.models.signals import post_save

# Create your models here.
class NewsletterSignup(models.Model):

    first_name = models.CharField(max_length=30, null=True, blank=False)
    last_name = models.CharField(max_length=30, null=True, blank=False)
    school = models.CharField(max_length=50, null=True, blank=False)
    year = models.CharField(max_length=50, null=True, blank=False)
    area_of_interest = models.CharField(max_length=100, null=True, blank=False)
    email = models.EmailField()
    signup_date = models.DateTimeField('Date Signed Up', auto_now_add=True)

    def __str__(self):
        return self.email

class CompletedActivity(models.Model):
    completed_date = models.DateTimeField('Date Completed', auto_now_add=True)
    activity = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name = 'completed activity'
        verbose_name_plural = 'completed activity'
        ordering = ('activity',)

class WorkshopUser(models.Model):
    LEVELS = (
        ('0', '0 - Baby'),
        ('1', '1 - Pre-schooler'),
        ('2', '2 - Primary-schooler'),
        ('3', '3 - Teenager'),
        ('4', '4 - Undergraduate'),
        ('5', '5 - Master'),
        ('6', '6 - Teacher'),
        ('7', '7 - Doctor'),
        ('8', '8 - Researcher'),
        ('9', '9 - Professor'),
        ('10', '10 - Astronaut'),
        ('11', '11 - Mad Scientist'),
        ('12', '12 - Superhero'),
        ('13', '13 - Advanced Alien'),
        ('14', '14 - Wizard'),
        ('15', '15 - Supercomputer'),
        ('16', '16 - Skynet'),
        ('17', '17 - Unicorn'),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    level = models.CharField(choices=LEVELS, max_length=100, default='0')
    ethics_approval = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name = 'workshop details'
        verbose_name_plural = 'workshop details'

def create_workshop_user(sender, instance, created, **kwargs):
    if created:
        WorkshopUser.objects.create(user=instance)

post_save.connect(create_workshop_user, sender=User)

home/views.py
import json

from django.shortcuts import render
from django.views import generic
from django.views.generic.edit import CreateView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import redirect
from django.contrib.auth import authenticate, login
from django.template import RequestContext

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.conf import settings

from django.template.loader import get_template

from home.forms import UserCreateForm, NewsletterForm, EreaderForm

from reportlab.pdfgen import canvas

from django.apps import apps



# from weasyprint import HTML, CSS

# def get_report(request):
#     html_template = get_template('home/other_research.html')

#     rendered_html = html_template.render(RequestContext(request)).encode(encoding="UTF-8")

#     pdf_file = HTML(string=rendered_html).write_pdf(stylesheets=[CSS(settings.STATICFILES_DIRS[0] +  '/css/main.css')])

#     http_response = HttpResponse(pdf_file, content_type='application/pdf')
#     http_response['Content-Disposition'] = 'filename="report.pdf"'

#     return http_response

# Create your views here.
class Index(generic.TemplateView):

    template_name = 'home/index.html'

    def dispatch(self, request, *args, **kwargs):
        # check if user is already logged in
        if request.user.is_authenticated():
            return redirect('home:dashboard')
        else:
            return super(Index, self).dispatch(request, *args, **kwargs)

def eyegazeinfo(request):
    return render(request, 'home/eyegazeinfo.html')

def get_completes(request):
     # Create list of all the apps that they've finished
    list_of_completes = []
    for item in request.user.completedactivity_set.all():
        list_of_completes.append(item.activity)

    return list_of_completes

@login_required
def dashboard(request):
    if request.method == 'POST':
        form = NewsletterForm(request.POST)
        if form.is_valid():
            new_newsletter_signup = form.save()
            return HttpResponseRedirect("/")
    else:
        form = NewsletterForm()

        # Create list of all the apps that they've finished
        list_of_completes = get_completes(request)

        # Check if a session variable has been set for previously visiting the dashboard
        if request.session.get('visited', False) is True:
            # If the variable exists, the user has visited
            # Pass a variable to javascript to say the user has visited
            greeting = ['Welcome back, ' + request.user.first_name + '!',
                        'Try another one, ' + request.user.first_name + '!',
                        'Hello again, ' + request.user.first_name + '.',
                        'Hello, ' + request.user.first_name + '.',
                        'Having fun, ' + request.user.first_name + '?',
                        'Good Morning, ' + request.user.first_name + '.',
                        'Nice to see you, ' + request.user.first_name + '!',
                        'Hi there, ' + request.user.first_name + '!'
                       ]
            context = {
                'visited' : True, 'form' : form,
                'greeting' : greeting,
                'completes' : list_of_completes}
            return render(request, 'home/dashboard.html', context)
        else:
            # Create the variable if it doesnt exist to say the user has visited
            # Pass a variable to javascript to say the user has not visited
            # (and hence display instructions)
            greeting = [
                'Let\'s get started, ' + request.user.first_name + '!',
                'Welcome, ' + request.user.first_name + '!']
            request.session['visited'] = True
            context = {
                'visited' : False, 'form' : form,
                'greeting' : greeting,
                'completes' : list_of_completes}
            return render(request, 'home/dashboard.html', context)


class About(generic.TemplateView):

    template_name = 'home/about.html'

    def dispatch(self, request, *args, **kwargs):
        # check if user is already logged in
        if request.user.is_authenticated():
            return redirect('home:dashboard')
        else:
            return super(About, self).dispatch(request, *args, **kwargs)

def register(request):
    if request.method == 'POST':
        form = UserCreateForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            new_user = authenticate(username=new_user.username,
                                    password=form.cleaned_data['password1'],
                                   )
            login(request, new_user)
            return HttpResponseRedirect("/dashboard")
    else:
        form = UserCreateForm()
    return render(request, "home/register.html", {
        'form': form,
    })

def newsletter(request):
    if request.method == 'POST':
        form = NewsletterForm(request.POST)
        if form.is_valid():
            new_newsletter_signup = form.save()
            return redirect('home:dashboard')
    else:
        prepop = {'first_name' : request.user.first_name, 'last_name' : request.user.last_name}
        form = NewsletterForm(initial=prepop)
        return render(request, "home/newsletter.html", {
            'form': form,
        })

def generate_webpage(request):
    # Create the HttpResponse object with the appropriate PDF headers.
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="somefilename.pdf"'

    buffer = BytesIO()

    # Create the PDF object, using the BytesIO object as its "file."
    p = canvas.Canvas(buffer)

    # Draw PDF
    p.drawString(100, 100, "Hello world.")

    # Close the PDF object cleanly.
    p.showPage()
    p.save()

    # Get the value of the BytesIO buffer and write it to the response.
    pdf = buffer.getvalue()
    buffer.close()
    response.write(pdf)
    return response

@method_decorator(login_required, name='dispatch')
class OtherResearch(generic.TemplateView):
    template_name = 'home/other_research.html'

@method_decorator(login_required, name='dispatch')
class eeg(generic.TemplateView):
    template_name = 'home/eeg.html'

@login_required
def eeg_activity(request):

    list_of_completes = get_completes(request)
    context = {'completes' : list_of_completes}

    return render(request, 'home/eeg-activity.html', context)

@method_decorator(login_required, name='dispatch')
class driving_simulator(generic.TemplateView):
    template_name = 'home/driving_simulator.html'

@login_required
def driving_activity(request):

    list_of_completes = get_completes(request)
    context = {'completes' : list_of_completes}

    return render(request, 'home/driving-activity.html', context)

@login_required
def interface_design(request):
    list_of_completes = get_completes(request)
    context = {'completes' : list_of_completes}

    return render(request, 'home/interface_design.html', context)

@login_required
def ereader_activity(request):

    form = EreaderForm()
    list_of_completes = get_completes(request)
    context = {'completes' : list_of_completes, 'form' : form}

    return render(request, 'home/ereader-activity.html', context)

@login_required
def ecg_activity(request):

    list_of_completes = get_completes(request)
    context = {'completes' : list_of_completes}

    return render(request, 'home/ecg-activity.html', context)

@method_decorator(login_required, name='dispatch')
class ecg(generic.TemplateView):
    template_name = 'home/ecg.html'

@method_decorator(login_required, name='dispatch')
class eda(generic.TemplateView):
    template_name = 'home/eda.html'

@login_required
def eda_activity(request):

    list_of_completes = get_completes(request)
    context = {'completes' : list_of_completes}

    return render(request, 'home/eda-activity.html', context)

@method_decorator(login_required, name='dispatch')
class gestures(generic.TemplateView):
    template_name = 'home/gestures.html'

@login_required
def gestures_activity(request):

    list_of_completes = get_completes(request)
    context = {'completes' : list_of_completes}

    return render(request, 'home/gestures-activity.html', context)

@login_required
def levelUp(request):
    user = request.user
    activity_path = request.POST['app_name']

    list_of_completes = []

    for item in user.completedactivity_set.all():
        list_of_completes.append(item.activity)

    if activity_path not in list_of_completes:
        new_completion = user.completedactivity_set.create(activity=activity_path)
        user.workshopuser.level = str(user.completedactivity_set.count()) # Must be a str
        user.workshopuser.save()

        new_level = user.workshopuser.get_level_display()
        increase = True

        data = {"new_level" : new_level, "increase" : increase}
        return HttpResponse(
            json.dumps(data),
            content_type="application/json"
        )
    else:
        new_level = user.workshopuser.get_level_display()
        increase = False
        data = {"new_level" : new_level, "increase" : increase}
        return HttpResponse(json.dumps(data), content_type="application/json")

home/templates/home/about.html
{% extends "base.html" %}
{% load staticfiles %}
{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'home/css/cover.css' %}" />
{% endblock %}
{% block body %}
    <div class="site-wrapper">
      <div class="site-wrapper-inner">
        <div class="cover-container">
          <div class="masthead clearfix">
            <div class="inner">
              <h3 class="masthead-brand"><a href="{% url 'home:index' %}">ANU HCC Workshop</a></h3>
              <nav>
                <ul class="nav masthead-nav">
                  <li class="active"><a href="{% url 'home:about' %}">About</a></li>
                  <li><a href="{% url 'login' %}">Login</a></li>
                  <li><a href="{% url 'home:register' %}">Register</a></li>
                </ul>
              </nav>
            </div>
          </div>
          <div class="inner cover">
            <h2>What is Human Centred Computing (HCC)?</h2>
            <p class="text-justify">When we interact and cooperate with other humans, they usually understand and predict what we will do. The same cannot be said of computers, which usually wait to be told what to do next. Using the latest technology, our research explores computer-human interactions with data and the world. We want computers to understand what users’ goals are when they perform specific tasks, and to enhance their user experience. Our goal is to make computers to 'think ahead', and be responsive in their interactions with humans.</p>
            <h2>What do we research?</h2>
            <p class="text-justify">We conduct interdisciplinary research, combining computing, art, science, music, security, psychology, social network analysis, digital humanities and biologically inspired computing.</p>
            <p class="text-justify">We are particularly interested in: interactive tools for supporting creativity in music and art; the use of wearable and mobile devices; control gestures for computer systems; health applications; virtual and augmented reality; and the use of eye-gaze and physiological signals to infer humans’ mental states.</p>
          </div>

          <div class="mastfoot">
            <div class="inner">
            </div>
          </div>

        </div>

      </div>

    </div>
{% endblock %}

home/templates/home/eda-activity.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %} 
HCC Workshop | Using the Empatica E4 for EDA
{% endblock %}

{% block app-breadcrumbs %}
<li><a href="{% url 'home:eda' %}">Electrodermal Activity</a></li>
<li class="active">Using the Empatica E4 for EDA</li>
{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'home/css/signals.css' %}">
{% endblock %}

{% block content %} 
<div class="content-container">
	<section class="titlebar">
		<h1 class="vertical-align animated bounceInLeft">Using the Empatica E4 for EDA</h1>
	</section>
	<section class="main-content">
		<p class="lead text-center">In this activity, you will be able to use an Empatica E4 on yourself in order to visualise your EDA activity.</p>
		<div class="text-center" style="margin: 16px 0">
			<img src="{% static 'home/images/e4-00.jpg' %}" alt="empatica_results" width="872"/>
		</div>
		<h2>Initial Setup</h2>
		<p class="text-justify">You will need:
			<ul>
				<li>An iPad</li>
				<li>An Empatica E4</li>
			</ul>
			A number of these devices will be available at the front of the room. Feel free to grab both an iPad and an E4 and take it back to your workstation.</p>
		<p class="text-justify"><strong>There are only a limited number of devices available, so if there are no devices free, you may need to attempt another activity in the meantime.</strong></p>
		<p class="text-justify">You can complete this activity individually. You can also work with your colleagues in order to compare how your electrodermal activity might be different to theirs.</p>
		<h2>Putting the E4 on</h2>
		<p class="text-justify">
			<div class="row">
				<div class="col-sm-8 col-md-8 col-lg-8">
					<ol>
						<li>
							<h4>Place the E4 on your wrist</h4>
							<p class="text-justify">You can choose whichever wrist you like. The single button is usually placed so that it is on the same side as your little pinky finger. The E4 should sit snug just next to your wrist joint.</p>
						</li>
						<li>
							<h4>Secure the strap</h4>
							<p class="text-justify">Wrap the strap around your wrist and secure both connections. Ensure that the strap is firm, but not too tight so that it hurts you.</p>
						</li>
					</ol>
				</div>
				<div class="col-sm-4 col-md-4 col-lg-4">
					<div class="text-center" style="margin: 16px auto">
						<img src="{% static 'home/images/e4-0.jpg' %}" alt="empatica_results" width="250"/>
					</div>
				</div>
			</div>
		</p>
		<h2>Pairing the devices</h2>
		<p class="text-justify">Once the Empatica E4 is firmly secured to your wrist, you need to pair the device to the iPad.</p>
		<div class="row">
			<div class="col-sm-8 col-md-8 col-lg-8">
				<ol>
					<li>
						<h4>Launch the Empatica Realtime application</h4>
						<p class="text-justify">Launch the application by touching the EmpaticaRT icon on the iPad. It should be on the third home screen.</p>
					</li>
					<li>
						<h4>Prepare the E4</h4>
						<p class="text-justify">Hold down the button on the Empatica E4 for 3 seconds. When a green light starts blinking, this indicates that the E4 is in pairing mode.</p>
					</li>
					<li>
						<h4>Start A New Session</h4>
						<p class="text-justify">Touch Start A New Session. The app will now search for nearby devices in pairing mode. Select the Empatica E4 device as it appears in the selection list. If nothing happens at first, try starting a new session again.</p>
					</li>
					<li>
						<h4>Off you go!</h4>
						<p class="text-justify">Once the pair is successful, the app will re-direct you to the Real Time Streaming.</p>
					</li>
				</ol>
			</div>
			<div class="col-sm-4 col-md-4 col-lg-4">
				<div class="text-center" style="margin: 16px 0">
					<img src="{% static 'home/images/e4-1.jpg' %}" alt="empatica_results" width="180"/>
				</div>
				<div class="text-center" style="margin: 16px 0">
					<img src="{% static 'home/images/e4-2.jpg' %}" alt="empatica_results" width="180"/>
				</div>
				<div class="text-center" style="margin: 16px 0">
					<img src="{% static 'home/images/e4-3.jpg' %}" alt="empatica_results" width="180"/>
				</div>
			</div>
		</div>
		<h2>Viewing your EDA</h2>
		<p class="text-justify">You can now see your electrodermal activity being tracked in real time. Awesome!</p>
		<div class="text-center" style="margin: 16px 0">
			<img src="{% static 'home/images/ecg-viewing.jpg' %}" alt="empatica_results" width="872"/>
		</div>
		<p class="text-justify">Using your fingers, pinch in and out in order to zoom and change the temporal resolution.</p>
		<h2><span class="activity-highlight">Activity: </span>Attempt to change your EDA</h2>
		<p class="text-justify">Let's see if we can trick your sympathetic nervous system into changing your electrodermal activity.</p>
		<p class="text-justify">Observe your EDA on the iPad. Take a note of its current level, then watch the following video.</p>
		<iframe width="872" height="490" src="https://www.youtube.com/embed/kBftA3M7Hck?modestbranding=1&autohide=1&showinfo=0&controls=0" frameborder="0" allowfullscreen></iframe>
		<p class="text-center lead">Did you notice any change?</p>
		<p class="text-center">If that didn't calm you, maybe try the next video.</p>
		<iframe width="872" height="490" src="https://www.youtube.com/embed/FGD_0IQiEbg?modestbranding=1&autohide=1&showinfo=0&controls=0" frameborder="0" allowfullscreen></iframe>
		<p class="text-justify">Okay sorry, maybe that was a bit mean. Did you notice any changes in your EDA activity during the second video? Inciting <em>fight-or-flight</em> responses can have an observable impact on your physiological signals. By monitoring changes in your electrodermal activity, we could infer the occurrence of neurological processes brought on by an external stimuli, such as seeing something frightening.</p>
		<h2><span class="activity-highlight">Activity: </span>Compare your data</h2>
		<p class="text-justify">Take a note of your EDA levels, and compare it to one of your friends. Are there any major differences in your EDA and theirs?</p>
		<p class="text-justify">Discuss with your friend why you might think that would be.</p>
		<h2>Cleaning Up</h2>
		<p class="text-justify">Once you've had enough, take the E4 off your wrist and hold down the button for 2 seconds. Turn off the iPad screen for the next person.</p>
	</section>
	<section class="sidebar text-center">
		<div class="sidebar-info-title">
			<i class="fa fa-question-circle fa-3x" aria-hidden="true"></i>
		</div>
		<div class="sidebar-content">
			<h2>Using iOS?<br>Tired of waiting?</h2>
			<p>Install the free Empatica Realtime application from the App Store and view your EDA on your own device!</p>
			<p>Just ask an Instructor for an E4.</p>
		</div>
		{% if '/ecg/empatica-ecg-activity' in completes %}
		<div class="sidebar-info-title">
			<i class="fa fa-exclamation-triangle fa-3x" aria-hidden="true"></i>
		</div>
		<div class="sidebar-content">
			<h2>Be courteous</h2>
			<p>Once finished with this activity, please return the iPad and Empatica E4 devices to the front for your colleagues to try.</p>
		</div>
		{% else %}
		<div class="sidebar-info-title">
			<i class="fa fa-info-circle fa-3x" aria-hidden="true"></i>
		</div>
		<div class="sidebar-content">
			<h2>Hold on!</h2>
			<p>The Empatica E4s also collect ECG data. Hold on to the iPad and E4 in order to learn about ECG.</p>
			<a href="{% url 'home:ecg' %}" class="btn btn-default btn-lg">Go to ECG</a>
		</div>
		{% endif %}
		{% if '/eda/empatica-eda-activity' not in completes %}
		<div class="sidebar-content sidebar-level">
			<h2>Level Up</h2>
			<p>Knees week? Palms sweaty?</p>
			<button role="button" class="btn btn-default btn-lg btn-level" href="#" id="level-up"><span class="btn-primary-span">Level Up</span><i class="fa fa-level-up" aria-hidden="true"></i></button>
		</div>
		{% endif %}
	</section>
</div>
{% endblock %}

{% block script %} 
{% endblock %}

home/templates/home/login.html
{% extends "core.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'home/css/cover.css' %}" />
{% endblock %}
{% block body %}
    <div class="site-wrapper">
      <div class="site-wrapper-inner">
        <div class="cover-container">
          <div class="masthead clearfix">
            <div class="inner">
              <h3 class="masthead-brand"><a href="{% url 'home:index' %}">ANU HCC Workshop</a></h3>
              <nav>
                <ul class="nav masthead-nav">
                  <li><a href="{% url 'home:about' %}">About</a></li>
                  <li class="active"><a href="{#% url 'login' %#}">Login</a></li>
                  <li><a href="{% url 'home:register' %}">Register</a></li>
                </ul>
              </nav>
            </div>
          </div>
          <div class="inner cover">
            <h1 style="font-size: 10vh">Login</h1>

            {% if user.is_authenticated %}
              <p>You are already logged in!</p>
              <p><a href="{% url 'home:dashboard' %}">Click here to go to your dashboard.</a></p>
              {% else %}
              <div style="width: 50%; margin: 0 auto;">
                {% crispy form %}
              </div>
            {% endif %}

          </div>

          <div class="mastfoot">
            <div class="inner">
              <small>By logging in and using this system, you agree to have your data used for research purposes. <a id="find-out-more">Find out more.</a></small>
            </div>
          </div>

        </div>

      </div>

    </div>
{% endblock %}

home/templates/home/logout.html
{% extends "base.html" %}
{% load staticfiles %}
{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'home/css/cover.css' %}" />
{% endblock %}
{% block body %}
    <div class="site-wrapper">
      <div class="site-wrapper-inner">
        <div class="cover-container">
          <div class="masthead clearfix">
            <div class="inner">
              <h3 class="masthead-brand"><a href="{% url 'home:index' %}">ANU HCC Workshop</a></h3>
              <nav>
                <ul class="nav masthead-nav">
                  <li><a href="{% url 'home:about' %}">About</a></li>
                  <li><a href="{% url 'login' %}">Login</a></li>
                  <li><a href="{% url 'home:register' %}">Register</a></li>
                </ul>
              </nav>
            </div>
          </div>
          <div class="inner cover">
            <h1 style="font-size: 10vh">Goodbye</h1>

            {% if user.is_authenticated %}
              <p>You are still logged in!</p>
              <p><a href="{% url 'home:dashboard' %}">Click here to go to your dashboard.</a></p>
              {% else %}
              <br><br>
                <p class="lead">Thank you for participating in the HCC Workshop. We hope you enjoyed it.
                    <br><br>
                If you have any feedback, we would love to hear it.</p>
            {% endif %}

          </div>

          <div class="mastfoot">
            <div class="inner">
              <small>By logging in and using this system, you agree to have your data used for research purposes. <a href="#">Find out more.</a></small>
            </div>
          </div>

        </div>

      </div>

    </div>
{% endblock %}

{% block script %}
{% endblock %}

home/templates/home/register.html
{% extends "core.html" %}
{% load staticfiles %}
{% load bootstrap3 %}
{% load crispy_forms_tags %}
{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'home/css/cover.css' %}" />
{% endblock %}
{% block body %}
    <div class="site-wrapper">
      <div class="site-wrapper-inner">
        <div class="cover-container">
          <div class="masthead clearfix">
            <div class="inner">
              <h3 class="masthead-brand"><a href="{% url 'home:index' %}">ANU HCC Workshop</a></h3>
              <nav>
                <ul class="nav masthead-nav">
                  <li><a href="{% url 'home:about' %}">About</a></li>
                  <li><a href="{% url 'login' %}">Login</a></li>
                  <li class="active"><a href="{% url 'home:register' %}">Register</a></li>
                </ul>
              </nav>
            </div>
          </div>
          <div class="inner cover">
            <h1 style="font-size: 10vh">Register</h1>
            <br>
            {% if user.is_authenticated %}
              <p>You are already logged in!</p>
              <p><a href="{% url 'home:dashboard' %}">Click here to go to your dashboard.</a></p>
              {% else %}
                {# Display a form #}
                <div style="width: 50%; margin: 0 auto;">
              {% crispy form %}
              </div>
            {% endif %}

          </div>

          <div class="mastfoot">
            <div class="inner">
              <small>By logging in and using this system, you agree to have your data used for research purposes. <a id="find-out-more">Find out more.</a></small>
            </div>
          </div>

        </div>

      </div>

    </div>
{% endblock %}

{% block script %}
<script>
$lol = $("#LOL");
$("#id_first_name, #id_last_name").keyup(function () {
    $lol.html(function () {
        return $('#id_first_name').map(function () {
            return this.value.toLowerCase().replace(" ","")
        }).get()+"."+$('#id_last_name').map(function () {
            return this.value.toLowerCase().replace(" ","")
        }).get();
    })
});
</script>
{% endblock %}