design/urls.py
## urls.py
from django.conf.urls import url

from . import views

app_name = 'design'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^mappings/$', views.mappings, name='mappings'),
    url(r'^affordances/$', views.affordances, name='affordances'),
    url(r'^constraints/$', views.constraints, name='constraints'),
    url(r'^conceptual-model/$', views.conceptual, name='conceptual'),
]

hccworkshop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from home.forms import LoginForm

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('home.urls')),
    url(r'^login/$', auth_views.login, {'template_name':'home/login.html', 'authentication_form':LoginForm}, name='login'),
    url(r'^logout/$', auth_views.logout, {'template_name':'home/logout.html'}, name='logout'),
    url(r'^eye-tracking/', include('eyetracking.urls')),
    url(r'^cyber-security/', include('cybersecurity.urls')),
    url(r'^the-thatcher-effect/', include('thatcher.urls')),
    url(r'^experiment/infovis/', include('collection.urls')),
    url(r'^human-computer-interaction/', include('design.urls')),
    url(r'^image-manipulation/', include('image_manipulation.urls')),
    url(r'^neural-networks/', include('neural_networks.urls')),
    url(r'^experiment/infovis/', include('collection.urls')),
    url(r'^surveys/', include('surveys.urls')),
]

admin.site.site_header = 'HCC Workshop Administration'

home/urls.py
from django.conf.urls import url
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm

from . import views

app_name = 'home'
urlpatterns = [
    url(r'^$', views.Index.as_view(), name='index'),
    url(r'^dashboard$', views.dashboard, name='dashboard'),
    url(r'^about$', views.About.as_view(), name='about'),
    url(r'^register$', views.register, name='register'),
    # url(r'^pdf$', views.get_report, name='pdf'),
    url(r'^eyegazeinfo/$', views.eyegazeinfo, name='eyegazeinfo'),
    url(r'^newsletter$', views.newsletter, name='newsletter'),
    # url(r'^other-research$', views.OtherResearch.as_view(), name='other_research'),
    url(r'^ecg$', views.ecg.as_view(), name='ecg'),
    url(r'^ecg/empatica-ecg-activity$', views.ecg_activity, name='ecg-activity'),
    url(r'^eeg$', views.eeg.as_view(), name='eeg'),
    url(r'^eeg/emotiv-activity$', views.eeg_activity, name='eeg-activity'),
    url(r'^eda$', views.eda.as_view(), name='eda'),
    url(r'^eda/empatica-eda-activity$', views.eda_activity, name='eda-activity'),
    url(r'^gestures$', views.gestures.as_view(), name='gestures'),
    url(r'^gestures/gestures-activity$', views.gestures_activity, name='gestures-activity'),
    url(r'^driving-simulator$', views.driving_simulator.as_view(), name='driving-simulator'),
    url(r'^driving-simulator/driving-activity$', views.driving_activity, name='driving-activity'),
    url(r'^interface-design$', views.interface_design, name='interface-design'),
    url(r'^interface-design/evaluating-ereader-interfaces$', views.ereader_activity, name='ereader-activity'),
    url(r'^level-up$', views.levelUp, name='levelup'),
]

design/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

MAPPINGS_CHOICES = (
    ('gmaps', 'Google Maps'),
    ('spatial', 'Using Spatial Reasoning'),
    ('notspatial', 'Not Using Spatial Reasoning'),
    ('compass', 'A Compass'),
)

CONSTRAINT_CHOICES = (
    ('stopuse', 'To stop a user from using an interface.'),
    ('coins', 'To teach people what Australian $2 coins look like.'),
    ('simplify', 'To help simplify the use of an interface.'),
)

class Mappings(models.Model):
    user = models.ForeignKey(User)
    timestamp = models.DateTimeField('Time Collected',auto_now_add=True)
    answer = models.CharField(choices=MAPPINGS_CHOICES, max_length=100, blank=False)
    correct = models.BooleanField()

class Constraints(models.Model):
    user = models.ForeignKey(User)
    timestamp = models.DateTimeField('Time Collected',auto_now_add=True)
    answer = models.CharField(choices=CONSTRAINT_CHOICES, max_length=100, blank=False)
    correct = models.BooleanField()

design/forms.py
from .models import Mappings, Constraints
from django import forms
from django.utils.translation import ugettext_lazy as _

class mappingsForm(forms.ModelForm):
    class Meta:
        model = Mappings
        fields = ['answer']
        labels = {
            'answer': _('What makes a good mapping?'),
        }
        widgets = {
            'answer': forms.RadioSelect(),
        }

class constraintForm(forms.ModelForm):
    class Meta:
        model = Constraints
        fields = ['answer']
        labels = {
            'answer': _('Why are constraints used?'),
        }
        widgets = {
            'answer': forms.RadioSelect(),
        }

design/views.py
## views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse, Http404
from .forms import mappingsForm, constraintForm
from .models import Mappings, Constraints
from django.core.urlresolvers import reverse
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib import messages

@login_required
def index(request):

    return render(request, 'design/index.html')

@login_required
def mappings(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = mappingsForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            messages.add_message(request, messages.INFO, "Level Up")
            mform = form.save(commit=False)
            mform.user = request.user
            answer = form.cleaned_data['answer']
            print(answer)
            if answer=='spatial':
                mform.correct = True
            else:
                mform.correct = False
            form.save()
            return HttpResponseRedirect(reverse('design:index'))
    # if a GET (or any other method) we'll create a blank form
    else:
        form = mappingsForm()

    return render(request, 'design/mappings.html', {'form': form})

@login_required
def affordances(request):
    return render(request, 'design/affordances.html')

@login_required
def constraints(request):
        # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = constraintForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            messages.add_message(request, messages.INFO, "Level Up")
            mform = form.save(commit=False)
            mform.user = request.user
            answer = form.cleaned_data['answer']
            print(answer)
            if answer=='simplify':
                mform.correct = True
            else:
                mform.correct = False
            form.save()
            return HttpResponseRedirect(reverse('design:index'))
    # if a GET (or any other method) we'll create a blank form
    else:
        form = constraintForm()

    return render(request, 'design/constraints.html', {'form': form})

@login_required
def conceptual(request):
    return render(request, 'design/conceptual.html')

design/templates/design/affordances.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %} HCC Workshop | Design Principles {% endblock %}
{% block head %}
	<link rel="stylesheet" href="{% static 'design/styles.css' %}">
{% endblock %}

{% block app-breadcrumbs %}
<li><a href="{% url 'design:index' %}">HCI </a></li>
	<li class="active">Affordances & Signifiers</li>
{% endblock %}

{% block content %} 
    <div class="container">
        <h2>Affordances & Signifiers</h2>
        <p class="text-justify">Affordances are a tricky concept to master because it is easily confused with the concept of mappings (which you may have already learnt) and signifiers. Affordances are nevertheless very important, because they help the user figure out what actions are possible without the need for labels or instructions. Affordances are relationships between an object or item and its use. An example of an affordance is a flat plate on a door, which gives the impression that the door must be pushed open, rather than pulled.</p>

        <h3 class="text-center">Affordances give STRONG cues on use</h3>

        <p class="text-justify">If affordances are thought of as determining what action is possible, then signifiers are the signal for what the action is. An examples is, if a button must be pushed, the signifier is the text on the button signalling what action the push is, such as “Delete” or “Enter”. Perceived affordances act as signifiers.</p>

        <h2>Opening doors can be very difficult</h2>
        <p class="text-justify">It may sound stupid at first, but opening doors isn't as straight forward as it often looks. How many times have you accidently pulled on a door that said right above the handle to push? If you are like the majority of people, this happens quite often.</p>

        


    </div>
{% endblock %}

{% block script %} 

{% endblock %}

design/templates/design/conceptual.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %} HCC Workshop | Design Principles {% endblock %}
{% block head %}
	<link rel="stylesheet" href="{% static 'design/styles.css' %}">
{% endblock %}

{% block app-breadcrumbs %}
<li><a href="{% url 'design:index' %}">HCI </a></li>
	<li class="active">Conceptual Models</li>
{% endblock %}

{% block content %} 
    <div class="page-header">
        <h1>HCI <small>CONCEPTUAL MODELS</small></h1>
    </div>
    <div class="container-fluid app-text-standard">
        <p class="text-justify">This design principle is one of the most important, because it integrates all of the design principles together. Conceptual models are how we think things works. They are mental models that help users understand the system and how to use it. Bad design of an interface can mess with the conceptual model and therefore its use! Conceptual models are formed through things like training, previous experience, and cultural expectations.</p>
        <p class="class-justify"></p>
    </div>
    <div class="container-fluid app-text-standard">
        <h2>Familiarity</h2>
        <p class="text-justify">When designing an interface it is really important to take into consideration what people probably already know. A lot of how people interact with an interface comes from their experiences or what they have been taught. This is called knowledge in the head! Knowledge in the head can be powerful when they build conceptual models of how a system or interface should work. That is why a lot of digital objects are similar to the real world.</p>
        <p class="text-justify">Another way of looking at it is that when designing interfaces one should stick to standards. These standards may be imposed by real world objects or they may be standards set by other systems. Going against standards that people have already learnt and know means it can be quite difficult for them to figure out how to use an interface. The clock below is an example of going against conceptual models.</p>
        <p class="text-center lead">How fast can you tell the time? </p>

        <div class="container">
        <canvas id="canvas" width="400" height="400" style="background-color:white"> </canvas>
        </div>

        <p class="text-justify">The clock doesn't conform to what your conceptual model of a clock is, it doesn't conform to the standard clock you learnt and it is therefore difficult for you to tell the time. The trick is that the numbers and hands are going in the opposite direction!</p>
    </div>
		<section class="container-fluid app-text-highlight">
				<div class="text-center vertical-align">
					<h1>Level Up</h1>
					<p class="lead">Time for a new level.</p>
					<button role="button" class="btn btn-default btn-lg" href="#" id="level-up"><span class="btn-primary-span">Level Up</span><i class="fa fa-level-up" aria-hidden="true"></i></a>
				</div>
</section>

    
{% endblock %}

{% block script %} 
<script type="text/javascript" src="{% static 'eyetracking/scroll.js' %}"></script>

<script>
var canvas = document.getElementById("canvas");
var ctx = canvas.getContext("2d");
var radius = canvas.height / 2;
ctx.translate(radius, radius);
radius = radius * 0.90
setInterval(drawClock, 1000);

function drawClock() {
  drawFace(ctx, radius);
  drawNumbers(ctx, radius);
  drawTime(ctx, radius);
}

function drawFace(ctx, radius) {
  var grad;
  ctx.beginPath();
  ctx.arc(0, 0, radius, 0, 2*Math.PI);
  ctx.fillStyle = 'white';
  ctx.fill();
  ctx.lineWidth = radius*0.05;
  ctx.stroke();
  ctx.beginPath();
  ctx.arc(0, 0, radius*0.07, 0, 2*Math.PI);
  ctx.fillStyle = 'black';
  ctx.fill();
}

function drawNumbers(ctx, radius) {
  var ang;
  var num;
  ctx.font = radius*0.15 + "px arial";
  ctx.textBaseline="middle";
  ctx.textAlign="center";
  for(num = 12; num > 0; num--){
    ang = -num * Math.PI / 6;
    ctx.rotate(ang);
    ctx.translate(0, -radius*0.85);
    ctx.rotate(-ang);
    ctx.fillText(num.toString(), 0, 0);
    ctx.rotate(ang);
    ctx.translate(0, radius*0.85);
    ctx.rotate(-ang);
  }
}

function drawTime(ctx, radius){
    var now = new Date();
    var hour = now.getHours();
    var minute = now.getMinutes();
    var second = now.getSeconds();
    //hour
    hour=hour%12;
    hour=(hour*Math.PI/6)+
    (minute*Math.PI/(6*60))+
    (second*Math.PI/(360*60));
    drawHand(ctx, hour, radius*0.4, radius*0.07);
    //minute
    minute=(minute*Math.PI/30)+(second*Math.PI/(30*60));
    drawHand(ctx, minute, radius*0.65, radius*0.07);
    // second
    second=(second*Math.PI/30);
    drawHand(ctx, second, radius*0.75, radius*0.02);
}

function drawHand(ctx, pos, length, width) {
    ctx.beginPath();
    ctx.lineWidth = width;
    ctx.lineCap = "round";
    ctx.moveTo(0,0);
    ctx.rotate(-pos);
    ctx.lineTo(0, -length);
    ctx.stroke();
    ctx.rotate(pos);
}
</script>

{% endblock %}

design/templates/design/index.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %} HCC Workshop | Design Principles {% endblock %}
{% block head %}
	<link rel="stylesheet" href="{% static 'design/styles.css' %}">
{% endblock %}

{% block app-breadcrumbs %}
	<li class="active">HCI </li>
{% endblock %}

{% block content %} 
	<div class="background-gif" id="reading-gif"></div>
	<div class="jumbotron text-center app-splash">
		<h1 class="vertical-align animated bounceInLeft" style="color: black;">Human Computer Interaction</h1>
	</div>
	<!-- Introduction section -->
	<section class="container-fluid app-text-standard">
		<p class="text-justify">Human Computer Interaction (HCI) is about the design, evaluation, and implementation of of computer systems that facilitates effective human use. HCI puts the human before anything else. </p>
		<p class="text-justify">But there are A LOT of poorly designed websites and software out there, I'm sure you have encountered many! Our goal is to introduce you to some design principles that can make interfaces better for interaction, and to hopefully interest you enough to come help us fight the battle against bad interface design!</p>
		<p class="text-justify">In this activity you will get to play some little activities that teach you some of the design principles that are fundamental in HCI. The more you play, the higher your skill level will become. See how skilled you can get and if you can beat your friends! </p> 
	</section>

	<section class="container-fluid app-text-other">
		<h3 class="text-center">“A user interface is like a joke, if you have to explain it, it's not that good” ~ unknown</h3>
	</section>
	
	<!-- Have students toggle images to find out what kind of subject areas HCI involves -->
	<div class="container-fluid app-text-standard subject-div">
		<h2>Subject areas</h2>
		<p class="text-justify">HCI is a very diverse and interesting research area. There are lots of different subjects areas that impact on, and are influenced by, HCI. In fact, there is so much you can do with HCI that no matter what you are interested in, there is something for you!</p>
		<p class="text-center lead" style="margin: 30px auto 50px auto; width: 45%;">Can you guess some of the subject areas involved in HCI? Click on each icon below to find out.</p>
		<div class="grid" style="margin: 0 auto; width: 22%">
					<div class="row">
						<div class="col-sm-4 col-md-4 col-lg-4 flipper" onclick="this.classList.toggle('flipped')">
							<div class="front text-center">
								<i class="fa fa-laptop fa-5x fa-fw" aria-hidden="true"></i>
							</div>
							<div class="back text-center">
								<i class="fa fa-laptop fa-5x fa-fw" aria-hidden="true"></i>
								<p>Computer Science</p>
							</div>
						</div>
						<div class="col-sm-4 col-md-4 col-lg-4 flipper" onclick="this.classList.toggle('flipped')">
							<div class="front text-center">
								<i class="fa fa-flask fa-5x fa-fw" aria-hidden="true"></i>
							</div>
							<div class="back text-center">
								<i class="fa fa-flask fa-5x fa-fw" aria-hidden="true"></i>
								<p>Psychology</p>
							</div>
						</div>
						<div class="col-sm-4 col-md-4 col-lg-4 flipper" onclick="this.classList.toggle('flipped')">
							<div class="front text-center">
								<i class="fa fa-paint-brush fa-5x fa-fw" aria-hidden="true"></i>
							</div>
							<div class="back text-center">
								<i class="fa fa-paint-brush fa-5x fa-fw" aria-hidden="true"></i>
								<p>Art</p>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-sm-4 col-md-4 col-lg-4 flipper" onclick="this.classList.toggle('flipped')">
							<div class="front text-center">
								<i class="fa fa-picture-o fa-5x fa-fw" aria-hidden="true"></i>
							</div>
							<div class="back text-center">
								<i class="fa fa-picture-o fa-5x fa-fw" aria-hidden="true"></i>
								<p>Design</p>
							</div>
						</div>
						<div class="col-sm-4 col-md-4 col-lg-4 flipper" onclick="this.classList.toggle('flipped')">
							<div class="front text-center">
								<i class="fa fa-music fa-5x fa-fw" aria-hidden="true"></i>
							</div>
							<div class="back text-center">
								<i class="fa fa-music fa-5x fa-fw" aria-hidden="true"></i>
								<p>Music</p>
							</div>
						</div>
						<div class="col-sm-4 col-md-4 col-lg-4 flipper" onclick="this.classList.toggle('flipped')">
							<div class="front text-center">
								<i class="fa fa-graduation-cap fa-5x" aria-hidden="true"></i>
							</div>
							<div class="back text-center">
								<i class="fa fa-graduation-cap fa-5x" aria-hidden="true"></i>
								<p>Education</p>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-sm-4 col-md-4 col-lg-4 flipper" onclick="this.classList.toggle('flipped')">
							<div class="front text-center">
								<i class="fa fa-user-secret fa-5x fa-fw" aria-hidden="true"></i>
							</div>
							<div class="back text-center">
								<i class="fa fa-user-secret fa-5x fa-fw" aria-hidden="true"></i>
								<p>Cyber Security</p>
							</div>
						</div>
						<div class="col-sm-4 col-md-4 col-lg-4 flipper" onclick="this.classList.toggle('flipped')">
							<div class="front text-center">
								<i class="fa fa-users fa-5x fa-fw" aria-hidden="true"></i>
							</div>
							<div class="back text-center">
								<i class="fa fa-users fa-5x fa-fw" aria-hidden="true"></i>
								<p>Sociology</p>
							</div>
						</div>
						<div class="col-sm-4 col-md-4 col-lg-4 flipper" onclick="this.classList.toggle('flipped')">
							<div class="front text-center">
								<i class="fa fa-keyboard-o fa-5x fa-fw" aria-hidden="true"></i>
							</div>
							<div class="back text-center">
								<i class="fa fa-keyboard-o fa-5x fa-fw" aria-hidden="true"></i>
								<p>Ergonomics</p>
							</div>
						</div>
					</div>
		</div>
	</div>
	<!-- Container for all of the activities -->
	<section class="container-fluid app-text-standard activities">
		<h2>Design Principles</h2>
		<p class="text-center lead" style="margin: 30px auto 50px auto; width: 45%;">Want more levels? Try out each of these activities.</p>
		<div class="row text-center" style="width: 73%; margin: 0 auto;">
			
			<a href="{% url 'design:mappings' %}">
				<div class="col-sm-4 col-md-4 col-lg-4 text-center bigger"> 
					<i class="fa fa-map-marker fa-5x fa-fw" aria-hidden="true"></i><h3 class="text-center">Mappings</h3>
				</div>
			</a>
			<a href="{% url 'design:constraints' %}">
				<div class="col-sm-4 col-md-4 col-lg-4 text-center bigger"> 
					<i class="fa fa-ban fa-5x fa-fw" aria-hidden="true"></i><h3 class="text-center">Constraints</h3>
				</div>
			</a>
			<!--<div class="col-sm-3 col-md-3 col-lg-3 text-center bigger"> 
				<a href="{% url 'design:affordances' %}">
				<i class="fa fa-map-signs fa-5x fa-fw" aria-hidden="true"></i><h3>Affordances & Signifiers</h3></a>
			</div>-->
			<a href="{% url 'design:conceptual' %}">
				<div class="col-sm-4 col-md-4 col-lg-4 text-center bigger"> 
					<i class="fa fa-bicycle fa-5x fa-fw" aria-hidden="true"></i><h3 class="text-center">Conceptual Models</h3>
				</div>
			</a>
		</div>

		
	</section>


{% endblock %}

{% block script %} 
{% if messages %}
{% for message in messages %}
<script>
$(function() {
	// If the user hasnt visited before, force display the instructions
	$('#level-modal').modal();
});
 </script>
 {% endfor %}
{% endif %}
{% endblock %}