cybersecurity/urls.py
from django.conf.urls import url

from . import views

app_name = 'cybersecurity'
urlpatterns = [
    url(r'^$', views.Index.as_view(), name='index'),
    url(r'^privacy$', views.privacy, name='privacy'),
    url(r'^phishing$', views.phishing, name='phishing'),
]

design/urls.py
## urls.py
from django.conf.urls import url

from . import views

app_name = 'design'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^mappings/$', views.mappings, name='mappings'),
    url(r'^affordances/$', views.affordances, name='affordances'),
    url(r'^constraints/$', views.constraints, name='constraints'),
    url(r'^conceptual-model/$', views.conceptual, name='conceptual'),
]

eyetracking/urls.py
## urls.py
from django.conf.urls import url

from . import views

app_name = 'eyetracking'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^join-the-dots/$', views.dots, name='join-the-dots'),
    url(r'^join-the-dots/results/$', views.joined_dots, name='join-the-dots-results'),
    url(r'^mouse-controller/$', views.controller.as_view(), name='mouse-controller'),
    url(r'^reading-analysis/$', views.reading, name='reading-analysis'),
    url(r'^reading-analysis/results/$', views.reading_gaze, name='reading-analysis-results'),
    url(r'^image-viewing/$', views.image, name='image-viewing'),
    url(r'^image-viewing/results/$', views.image_gaze, name='image-viewing-results'),
]

hccworkshop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from home.forms import LoginForm

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('home.urls')),
    url(r'^login/$', auth_views.login, {'template_name':'home/login.html', 'authentication_form':LoginForm}, name='login'),
    url(r'^logout/$', auth_views.logout, {'template_name':'home/logout.html'}, name='logout'),
    url(r'^eye-tracking/', include('eyetracking.urls')),
    url(r'^cyber-security/', include('cybersecurity.urls')),
    url(r'^the-thatcher-effect/', include('thatcher.urls')),
    url(r'^experiment/infovis/', include('collection.urls')),
    url(r'^human-computer-interaction/', include('design.urls')),
    url(r'^image-manipulation/', include('image_manipulation.urls')),
    url(r'^neural-networks/', include('neural_networks.urls')),
    url(r'^experiment/infovis/', include('collection.urls')),
    url(r'^surveys/', include('surveys.urls')),
]

admin.site.site_header = 'HCC Workshop Administration'

home/urls.py
from django.conf.urls import url
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm

from . import views

app_name = 'home'
urlpatterns = [
    url(r'^$', views.Index.as_view(), name='index'),
    url(r'^dashboard$', views.dashboard, name='dashboard'),
    url(r'^about$', views.About.as_view(), name='about'),
    url(r'^register$', views.register, name='register'),
    # url(r'^pdf$', views.get_report, name='pdf'),
    url(r'^eyegazeinfo/$', views.eyegazeinfo, name='eyegazeinfo'),
    url(r'^newsletter$', views.newsletter, name='newsletter'),
    # url(r'^other-research$', views.OtherResearch.as_view(), name='other_research'),
    url(r'^ecg$', views.ecg.as_view(), name='ecg'),
    url(r'^ecg/empatica-ecg-activity$', views.ecg_activity, name='ecg-activity'),
    url(r'^eeg$', views.eeg.as_view(), name='eeg'),
    url(r'^eeg/emotiv-activity$', views.eeg_activity, name='eeg-activity'),
    url(r'^eda$', views.eda.as_view(), name='eda'),
    url(r'^eda/empatica-eda-activity$', views.eda_activity, name='eda-activity'),
    url(r'^gestures$', views.gestures.as_view(), name='gestures'),
    url(r'^gestures/gestures-activity$', views.gestures_activity, name='gestures-activity'),
    url(r'^driving-simulator$', views.driving_simulator.as_view(), name='driving-simulator'),
    url(r'^driving-simulator/driving-activity$', views.driving_activity, name='driving-activity'),
    url(r'^interface-design$', views.interface_design, name='interface-design'),
    url(r'^interface-design/evaluating-ereader-interfaces$', views.ereader_activity, name='ereader-activity'),
    url(r'^level-up$', views.levelUp, name='levelup'),
]

thatcher/urls.py
## urls.py
from django.conf.urls import url

from . import views

app_name = 'thatcher'
urlpatterns = [
    url(r'^$', views.index, name='index'),
]

templates/base.html
{% extends "core.html" %}
{% load staticfiles %}
{% block body %}
<section class="help-overlay text-center" id="instructions">
      <h1>Instructions</h1>
      <p class="text-justify">The workshop consists of several activities that you are able to play with. Whenever you complete an activity, you will gain an extra level. You can view your current level by looking at the middle of the navigation bar at the top of the screen.<p>
      <p class="text-justify">This is a self-paced learning environment, allowing you to explore the entire website and complete the activities you want in whatever order or pace that suits you.<p>
      <p class="text-justify">If you have any questions, feel free to talk to one of the friendly ANU Ambassadors.</p>
      <p class="text-justify">When you are finished, please complete our feedback form to help improve the experience for others.</p>
      <button class="btn btn-lg btn-default" id="instructions-close-btn">Close</button>
</section>
<div id="wrapper" class="toggled"> 
    <header class="navbar navbar-default navbar-fixed-top">

            <button class="side-nav-toggle" data-toggle="offcanvas" title="Show Menu">
                <i class="fa fa-bars" aria-hidden="true"></i>
            </button>
            <ol class="breadcrumb title">
                {% if request.get_full_path == "/dashboard" %}
                    <li class="active">Dashboard</li>
                {% else %}
                    <li><a href="{% url 'home:dashboard' %}">Dashboard</a></li>
                    {% block app-breadcrumbs %}{% endblock %}
                {% endif %}
            </ol>
            <span class="navbar-fixed-top-level">{{ user.workshopuser.get_level_display }}</span>
            <span class="navbar-fixed-top-buttons">
                    <a href="{% url 'home:dashboard' %}" class="navbar-dashboard" title="Dashboard">
                        <i class="fa fa-home fa-lg fa-fw" aria-hidden="true"></i>
                    </a>
                    <a href="#" class="navbar-dashboard" title="Help" data-toggle="modal" data-target="#instructions-modal">
                        <i class="fa fa-info-circle fa-lg fa-fw" aria-hidden="true"></i>
                    </a>
                    <a href="{% url 'logout' %}" class="navbar-sign-out" title="Sign Out">
                        <i class="fa fa-sign-out fa-lg fa-fw" aria-hidden="true"></i>
                    </a>
            </span> 
    </header>
    <nav class="navbar navbar-inverse" id="sidebar-wrapper" role="navigation">  
        <ul class="nav sidebar-nav">
            <li class="sidebar-brand" title="Hide Menu">
                <i class="fa fa-bars" aria-hidden="true" data-toggle="offcanvas"></i>
            </li>
            <li>
                <a href="{% url 'home:dashboard' %}">
                    <i class="fa fa-home fa-lg fa-fw" aria-hidden="true"></i>
                    <span>Dashboard</span>
                </a>
            </li>
            <br>
            <li>
                <a href="{% url 'eyetracking:index' %}">
                    <i class="fa fa-eye fa-lg fa-fw" aria-hidden="true"></i>
                    <span>Eye Tracking</span></a>
            </li>
            <br>
            <li>
                <a href="{% url 'design:index' %}">
                    <i class="fa fa-desktop fa-lg fa-fw" aria-hidden="true"></i>
                    <span>HCI</span></a>
            </li>
            <li>
                <a href="{% url 'cybersecurity:index' %}">
                    <i class="fa fa-user-secret fa-lg fa-fw" aria-hidden="true"></i>
                    <span>Cyber Security</span></a>
            </li>
            <li>
                <a href="{% url 'image_manipulation:index' %}">
                    <i class="fa fa-picture-o fa-lg fa-fw" aria-hidden="true"></i>
                    <span>Manipulated Images</span></a>
            </li>
            <li>
                <a href="{% url 'home:ecg' %}">
                    <i class="fa fa-heartbeat fa-lg fa-fw" aria-hidden="true"></i>
                    <span>ECG</span></a>
            </li>
            <li>
                <a href="{% url 'home:eeg' %}">
                    <i class="fa fa-heartbeat fa-lg fa-fw" aria-hidden="true"></i>
                    <span>EEG</span></a>
            </li>
            <br>
            <li>
                <a href="{% url 'thatcher:index' %}">
                    <i class="fa fa-frown-o fa-rotate-180 fa-lg fa-fw" aria-hidden="true"></i>
                    <span>The Thatcher Effect</span>
                </a>
            </li>
            <li>
                <a href="{% url 'neural_networks:index' %}">
                    <i class="fa fa-cogs fa-rotate-180 fa-lg fa-fw" aria-hidden="true"></i>
                    <span>Neural Networks</span>
                </a>
            </li>
            {% block menu %}
            {% endblock %}
            <br><br>
            <li class="sidebar-sign-out">
                <a href="{% url 'logout' %}">
                    <i class="fa fa-sign-out fa-lg fa-fw" aria-hidden="true"></i>
                    <span>Logout</span>
                </a> 
            </li>
            <li>
                <p class="text-center" style="color: white; margin: 12px 0; font-size:1vw">You are logged in as <br>{{ user.username }}</p>
            </li>
        </ul>
    </nav> 
        <div id="page-content-wrapper" >
            <div id="content" class="container-fluid">
            {% block content %}
            {% endblock %}
                <section class="app-footer">
                    <div class="row">
                        <div class="col-md-6">
                            <h3>Human Centred Computing Workshop</h3>
                            <p>Research School of Computer Science<br>College of Engineering and Computer Science<br>The Australian National University</p>
                            <p>© 2016 ANU HCC <span id="find-out-more" style="margin-left: 160px">Privacy Policy</span></p>
                        </div>
                        <div class="col-md-6">
                            <div class="row">
                                <div class="col-md-6">
                                    <p class="lead lead-footer"><strong>Visit</strong></p>
                                    <ul class="list-footer">
                                        <li><a href="http://www.anu.edu.au/">ANU Website</a></li>
                                        <li><a href="https://cecs.anu.edu.au/">CECS Website</a></li>
                                        <li><a href="https://cecs.anu.edu.au/research/systems/human-centred-computing">HCC Group</a></li>
                                    </ul>
                                </div>
                                <div class="col-md-6">
                                    <p class="lead lead-footer"><strong>Connect</strong></p>
                                    <ul class="list-footer">
                                        <li><a href="https://www.facebook.com/anu.cecs">Facebook</a></li>
                                        <li><a href="https://twitter.com/anucecs">Twitter</a></li>
                                        <li><a href="https://instagram.com/ouranu">Instagram</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div> 
                    </div>
                </section>
            </div>
           
        </div><!-- /#page-content-wrapper -->

</div><!-- /#wrapper -->
{% endblock %}